on:
  pull_request:
    branches:
      - main
name: CI Workflow
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup node 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - run: npx lerna bootstrap
      - run: npm run lint
      - run: npm run test
      - run: git diff --exit-code
